

services:
  frontend:
    build: ./frontend
    ports:
      - "3001:80"
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
    networks:
      - chat-network

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
    depends_on:
      - db
    networks:
      - chat-network

  db:
    image: mariadb:10.11
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=chatdb
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - chat-network

volumes:
  db_data:

networks:
  chat-network:
    driver: bridge