version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
    networks:
      - chat-network

  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=${DB_HOST:-db}
      - DB_USER=root
      - DB_PASSWORD=secret
      - DB_NAME=chatdb
    depends_on:
      - db
    networks:
      - chat-network

  db:
    image: mariadb:10.11
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=chatdb
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - chat-network

volumes:
  db_data:

networks:
  chat-network:
    driver: bridge
